@ProspectionCrm.Api_HostAddress = http://localhost:5016

### Document OpenAPI disponible en environnement Development
GET {{ProspectionCrm.Api_HostAddress}}/openapi/v1.json
Accept: application/json

###
